"""BD

Revision ID: 25cc06e09d7b
Revises: 992abc3bb184
Create Date: 2021-10-26 13:30:35.691201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cc06e09d7b'
down_revision = '992abc3bb184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contract', sa.Column('Files', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Contract', 'Files')
    # ### end Alembic commands ###
