"""BD

Revision ID: 2b21fff7e3e7
Revises: 
Create Date: 2021-10-11 09:05:25.433923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b21fff7e3e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'ip',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('Users', 'user_name',
               existing_type=mysql.VARCHAR(length=21),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'user_name',
               existing_type=mysql.VARCHAR(length=21),
               nullable=True)
    op.alter_column('Users', 'ip',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
