"""BD

Revision ID: 992abc3bb184
Revises: 2b21fff7e3e7
Create Date: 2021-10-11 10:38:28.792723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '992abc3bb184'
down_revision = '2b21fff7e3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Contract', 'id',
               existing_type=mysql.INTEGER(display_width=2),
               nullable=False,
               autoincrement=True)
    op.alter_column('Contract', 'NumCont',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('Contract', 'Date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('Contract', 'We',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('Contract', 'They',
               existing_type=mysql.VARCHAR(length=42),
               nullable=False)
    op.alter_column('Contract', 'View',
               existing_type=mysql.VARCHAR(length=31),
               nullable=False)
    op.alter_column('Contract', 'Thing',
               existing_type=mysql.VARCHAR(length=88),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Contract', 'Thing',
               existing_type=mysql.VARCHAR(length=88),
               nullable=True)
    op.alter_column('Contract', 'View',
               existing_type=mysql.VARCHAR(length=31),
               nullable=True)
    op.alter_column('Contract', 'They',
               existing_type=mysql.VARCHAR(length=42),
               nullable=True)
    op.alter_column('Contract', 'We',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('Contract', 'Date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('Contract', 'NumCont',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('Contract', 'id',
               existing_type=mysql.INTEGER(display_width=2),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
